# istio-statsd-prom-bridge docker compose file
version: '2'
services:
  istio-telemetry:
    network_mode: "bridge"
    ports:
      - "9091:9091"
    container_name: istio-telemetry
    volumes:
      # - /sock:/home/ubuntu/lb/mixer/istio-telemetry-uds-socket
      - /home/ubuntu/lb/mixer/istio-telemetry-uds-socket:/sock
      - ./kubeconfig:/etc/istio/config/kubeconfig
    image: gcr.io/istio-release/mixer:1.0.0
    environment:
      - SERVICE_IGNORE=1
    command: 
      - --address
      - unix:///sock/mixer.socket
      - --configStoreURL=k8s:///etc/istio/config/kubeconfig
      - --configDefaultNamespace=istio-system
      - --trace_zipkin_url=http://172.167.40.24:9411/api/v1/spans

  istio-telemetry-sidecar:
    image: service-mesh/mesh_sidecar:0.1
    network_mode: "service:istio-telemetry"
    # network_mode: "container:istio-telemetry"
    command:
      - proxy
      - --serviceCluster
      - istio-telemetry
      # - --serviceregistry Consul
      - --templateFile
      - /etc/istio/proxy/envoy_telemetry.yaml.tmpl
      - --controlPlaneAuthPolicy
      - NONE 
      #- "/usr/local/bin/pilot-agent proxy --serviceregistry Consul --serviceCluster istio-telemetry --configPath /var/lib/istio >/tmp/envoy.log"

